namespace CarEyePlayerDemo.Player
{
	internal enum CE_AUDIO_VISUAL_EFFECT_MODE
	{
		AUDIO_VISUAL_EFFECT_DISABLE,

		AUDIO_VISUAL_EFFECT_WAVEFORM,

		AUDIO_VISUAL_EFFECT_SPECTRUM,

		AUDIO_VISUAL_EFFECT_MAX_NUM,
	}
}
